### PR TITLE
Use Netty's MqttMessageBuilders when possible

### LINKED ISSUE #13: Consider usage of new MqttMessageBuilders from Netty

### PR DESCRIPTION
**Pull request by francois-travais**
Fixes #13.
We cannot use `MqttMessageBuilders` for `PUBLISH` messages because the implementation forces `isDup` to `false`.

### CODE REVIEW

**Comment by ppatierno** [comment]
@francois-travais can you check and resolve conflicts before I start the review please? Thanks!

**Comment by vietj** [comment]
ping @francois-travais

**Comment by vietj** [comment]
@francois-travais ping

**Comment by vietj** [comment]
we would like to merge this in master for Vert.x 4

**Comment by francois-travais** [comment]
@vietj I rebased. I'm not sure whether the failing tests are a consequence of the changes I made.

**Comment by vietj** [comment]
@francois-travais can you rebase again, then we can merge it for 4.0.1

**Pull request closed without merging**
