### PR TITLE
Expose peer certificates

### PR DESCRIPTION
**Pull request by sauthieg**

### CODE REVIEW

**Comment by sauthieg** [comment]
Any chance to have this simple fix in 3.4.2 ?

**Comment by ppatierno** [comment]
What I see from current Java 8 documentation here (https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSession.html) about the getPeerCertificateChain() method is that : "this method exists for compatibility with previous releases. New applications should use getPeerCertificates() instead." The getPeerCertificates() is not exposed by ConnectionBase, so I'm thinking if it's worth to add this. Wdyt @vietj ?

**Comment by sauthieg** [comment]
Makes sense to me not to rely on deprecated methods :)
I've simply adapted what was already in the HTTP codebase.

Do you want to first add theses new methods on `ConnectionBase`, and then use them in the `MqttEndpointImpl` ?

**Comment by dachaac** [comment]
There is now PR for vert.x to add support for peerCertificates():
https://github.com/eclipse/vert.x/pull/2078

To test it out I created fork+branch for vertx-mqtt:
https://github.com/dachaac/vertx-mqtt/tree/peercertificate-support

It has some additional changes vs. this PR.

With these two changes I was able to identify from SSL Client Certificate what MQTT client connected to vert.x mqtt based server.

**Comment by ppatierno** [comment]
while waiting for the Vert.x PR got merged, @sauthieg can you check and fix the conflicts on this ?

**Comment by dachaac** [comment]
@sauthieg + @ppatierno: PR for vert.x is now merged. It added sslSession() support for sockets which can be used to acquire information about SSLSession including peer's SSL Client Certificates.

I have updated my branch for vertx-mqtt to match this and tested that it still works with my test application.

Do you want to update this PR with matching changes or shall I create a PR from my branch?

**Comment by laurentvaills** [comment]
@dachaac Thanks for the other merged PR. I'm working with @sauthieg and he might not have Internet access during the next days. IMO, he shall agree that you create a PR from your branch so we can go on on this subject.
The SSLSession gives access to more information than just the peer certificates.

**Comment by dachaac** [comment]
I have just created PR from my changes for sslSession() based approach: https://github.com/vert-x3/vertx-mqtt/pull/42

**Comment by ppatierno** [comment]
@sauthieg @dachaac are you ok if I close this PR and we consider to merge the #42 for that ?

**Comment by sauthieg** [comment]
@ppatierno Ok for me
My requirement is that I can get the connection's certificate somehow, either directly or through `sslSession()`.

**Comment by sauthieg** [comment]
Declining this PR in favour of #42

**Pull request closed without merging**
