### PR TITLE
Prepare for MQTT5 changes

### PR DESCRIPTION
**Pull request by paul-lysak**
Adapt for Netty `4.1.52.Final` in order to unlock the work on MQTT5 (https://github.com/vert-x3/vertx-mqtt/issues/161).
Depends on https://github.com/vert-x3/vertx-dependencies/pull/49.

### CODE REVIEW

**Comment by vietj** [comment]
ping us @paul-lysak when we can help you on the PR

**Comment by paul-lysak** [comment]
> ping us @paul-lysak when we can help you on the PR

This one is complete, let me know if you'd like to have something changed. It just wouldn't compile until https://github.com/vert-x3/vertx-dependencies/pull/49 is merged.

**Comment by vietj** [comment]
ok

**Comment by vietj** [comment]
@paul-lysak we are still waiting to update to Netty 4.1.52.Final for this contribution, currently this is blocked because vertx-grpc relies on a different version of Netty that cannot be coerced to 4.1.52.Final

**Comment by vietj** [comment]
@paul-lysak Netty 4.1.52.Final has been merged in master

**Comment by vietj** [comment]
@paul-lysak can you rebase this branch on master so it will use the new GitHub action based CI ?

**Comment by paul-lysak** [comment]
> @paul-lysak can you rebase this branch on master so it will use the new GitHub action based CI ?

Done

**Comment by vietj** [comment]
nice, CI is running now

**Comment by vietj** [comment]
@paul-lysak do you mind rebasing again onto the latest master ? we upgraded to Netty 4.1.58.Final (because 4.1.52.Final has some issues) and I had to fix a few things in order for implementation and tests to work

**Comment by paul-lysak** [comment]
> @paul-lysak do you mind rebasing again onto the latest master ? we upgraded to Netty 4.1.58.Final (because 4.1.52.Final has some issues) and I had to fix a few things in order for implementation and tests to work
Sure, just rebased

**Comment by vietj** [comment]
alright CI pass so we are good.

**Pull request merged**
